## This file must be checked in version control.
# https://kotlinlang.org/docs/reference/using-gradle.html#gradle-java-toolchain-support
kotlin.jvm.toolchain.version=17

# Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
org.gradle.daemon=true
org.gradle.parallel=true

# Android
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# Hilt
android.useNewApkCreator=true
